---
name: Run the Python Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/alan-tracy:latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Run tests.
        run: |
          make venv
          make report
          make test